### ISSUE TITLE
please remove this repository

### ISSUE THREAD

**Issue by CardealRusso** [cat-milk/Anime-Girls-Holding-Programming-Books#622]
It's cringe and doesn't contribute anything to technology

**Comment by kiraio-moe** [comment]
> It's cringe and doesn't contribute anything to technology

It's up to the owner what they want. Get some life.

**Comment by SoftwareGuy** [comment]
> It's cringe and doesn't contribute anything to technology

Go outside and touch some grass mate.

**Comment by GeorgeRNG** [comment]
yes!!!! we need to find all the pointless joke repositories which do not contribute anything to the progression of humanity! We need to search across all of GitHub for all these types of repositories and get them pulled down! (since trying to get joke repositories down contributes more to society then helping cool repos)
we should spend 100% of our lives contributing to humanity, who will then use their lives to contribute to humanity. Empower the worklife!

**Comment by welikethestock** [comment]
thats a (You) problem

**Comment by fcolecumberri** [comment]
> It's cringe and doesn't contribute anything to technology

says who?

If you want to do a presentation about a programming languages, what do you prefer? a slide only saying

```
<Programming language>
```

or a slide with a nice drawing that also represents the programming language. As communication resources this is useful.

Also, if you are worried about people spending their time on stuff that seems to have no contribution, try to think about Fermat's little theorem, it took 300 years to find a meaningful technological contribution for that theorem, now it's the core of secure communications.

**Comment by all123all** [comment]
Why does it bothers you so much? I mean, just close your eyes lmao
